// <auto-generated />
using Author.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Author.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssesementCandidate", b =>
                {
                    b.Property<int>("AssessmentsAssesementId")
                        .HasColumnType("int");

                    b.Property<int>("CandidatesCandidateId")
                        .HasColumnType("int");

                    b.HasKey("AssessmentsAssesementId", "CandidatesCandidateId");

                    b.HasIndex("CandidatesCandidateId");

                    b.ToTable("CandidateAssesements", (string)null);
                });

            modelBuilder.Entity("Author.Assesement", b =>
                {
                    b.Property<int>("AssesementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssesementId"));

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssesementId");

                    b.ToTable("Assesements");
                });

            modelBuilder.Entity("Author.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidateId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("AssesementCandidate", b =>
                {
                    b.HasOne("Author.Assesement", null)
                        .WithMany()
                        .HasForeignKey("AssessmentsAssesementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Author.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidatesCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
